# Prezto
source "$HOME/.zprezto/init.zsh"

# Aliases (should go in alias.zsh)
alias gs='git status'
alias gst='git stash'
alias gd='git diff'
alias gpl='git pull'
alias gps='git push'
alias ga='git add -A'
alias gc='git commit -am'
alias gcm='git commit -m'

alias vi=vim

alias ll='ls -alGh'
alias ls='ls -G'

alias rm='nocorrect rm'

# Colors
export TERM=xterm-256color
export CLICOLOR=1
export LSCOLORS=Gxfxcxdxbxegedabagacad

# Enable color in grep
export GREP_OPTIONS='--color=auto'
export GREP_COLOR='3;33'


HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# cd without typing cd
setopt AUTO_CD

setopt APPEND_HISTORY # Allow multiple terminal sessions to all append to one zsh command history
setopt INC_APPEND_HISTORY # Add comamnds as they are typed, don't wait until shell exit
setopt HIST_REDUCE_BLANKS # Remove extra blanks from each command line being added to history
setopt EXTENDED_HISTORY # Include more information about when the command was executed, etc

# Too slow
#source ~/.powerline/powerline/bindings/zsh/powerline.zsh
